# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20250913-004158-obliging-truss

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: "es"

pipeline:
- name: WhitespaceTokenizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 50
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 50
- name: FallbackClassifier
  threshold: 0.35
  ambiguity_threshold: 0.1
policies:
- name: RulePolicy
- name: MemoizationPolicy
- name: TEDPolicy
  epochs: 50

