# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20250913-004158-obliging-truss

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: "es"

pipeline:
  - name: WhitespaceTokenizer
    intent_tokenization_flag: false
  - name: RegexFeaturizer
    case_sensitive: false
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    min_ngram: 1
    max_ngram: 2
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 3
    max_ngram: 6
  - name: RegexEntityExtractor
    case_sensitive: false
    use_lookup_tables: true
    use_regexes: true
  - name: DIETClassifier
    epochs: 150
    constrain_similarities: true
    evaluate_on_number_of_examples: 150
    evaluate_every_number_of_epochs: 5
    early_stopping_patience: 8
    batch_strategy: "sequence"
    learning_rate: 0.002
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 75
    constrain_similarities: true
  - name: FallbackClassifier
    threshold: 0.35
    ambiguity_threshold: 0.05

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "utter_fuera_de_alcance"
    enable_fallback_prediction: true
  - name: TEDPolicy
    max_history: 8
    epochs: 80
    constrain_similarities: true
